spring:
  jpa:
    database: postgresql
    hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

spring.datasource:
  hikari.maximum-pool-size: 4
  url: jdbc:postgresql://ec2-3-221-175-22.compute-1.amazonaws.com/dsj4dj5jnksjh
  userName: dbmqozwznpxhlo
  password: 853c81b3088d52eee92b7b45019f24925d8967d3b6797829be78fb759d77ca77
  platform: postgres
  driver-class-name: org.postgresql.Driver

jwt:
  secret: YWJjZGVmZ2hpamtsbW5vcHFyc3R1dnd4eXo3ODkwMTIzNDU2Nzg5MGFiY2RlZmdoaWprbG1ub3BxcnN0dXZ3eHl6
  access-token-expire-time: 3600000
  refresh-token-expire-time: 5184000000


# UserDetailsService ? ????? ???? ???? ???? ?? ????? ??? ?? ???? ???? ??? ??.
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration