jwt:
  secret: 64461f01e1af406da538b9c48d801ce59142452199ff112fb5404c8e7e98e3ff
  access-token-expire-time: 3600000
  refresh-token-expire-time: 5184000000


# UserDetailsService 빈 자동등록을 해제하여 자동으로 생성되는 보안 비밀번호와 관련된 경고 메시지가 표시되지 않도록 한다.
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration